// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJX9V5mTobnLzHNtuX56YOLLstx1NV4z0',
    appId: '1:46917976454:android:4c0ad328c379dde1146c07',
    messagingSenderId: '46917976454',
    projectId: 'trackin-df4d8',
    storageBucket: 'trackin-df4d8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCS4ExPkfhTqF4I1echTt-CEzvtFPybTp4',
    appId: '1:46917976454:ios:f28957dd0e355de3146c07',
    messagingSenderId: '46917976454',
    projectId: 'trackin-df4d8',
    storageBucket: 'trackin-df4d8.firebasestorage.app',
    androidClientId: '46917976454-5mlkv53bocsgr3sfe8fmhlob7j1tcb2d.apps.googleusercontent.com',
    iosClientId: '46917976454-2dqsiqr0k9gt8q2u9he0d7qgq1bh27mg.apps.googleusercontent.com',
    iosBundleId: 'com.example.attendanceApp',
  );
}
